#! /bin/sh
#     _    _   _
#    / \  | | | | Arthur Hawron
#   / _ \ | |_| |  
#  / ___ \|  _  |
# /_/   \_\_| |_|
#
	  
#### AUTOSTART ####
sxhkd &
picom --experimental-backends &
nitrogen --restore &
xsetroot -cursor_name left_ptr &
xfce4-power-manager &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
/usr/lib/xfce4/notifyd/xfce4-notifyd &

#~/.config/polybar/launch.sh
#if [[ $(xrandr -q | grep 'HDMI-1 connected') ]]; then
#	xrandr --output eDP-1 --mode 1920x1080 --rotate normal --output HDMI-1 --primary --mode 1920x1080 --rotate normal --right-of eDP-1 &
#fi
~/.config/bspwm/scripts/startup

#### BSPWM configuration ####
bspc config border_width                  0
bspc config window_gap                    15
bspc config split_ratio                   0.50
bspc config borderless_monocle            true
bspc config gapless_monocle               false
bspc config focus_follows_pointer         true

bspc rule -a Gimp desktop='^4' state=floating follow=on
bspc rule -a steam desktop='^5' state=floating follow=on
bspc rule -a discord desktop='^6' follow=off


bspc monitor eDP-1 -d  1 2 3 4 5 6 7 8
